version: "3.9"
services:
  api-test:
    build: .
    env_file:
      - ./config/config.env
    # ports:
    #   - "4000:4000"
    volumes:
      - /usr/src/app
    command: npm test
    links:
      - api
  api:
    build: .
    env_file:
      - ./config/config.env
    ports:
      - "4000:4000"
    volumes:
      - /usr/src/app
    command: node server.js
